name: Git Version

on:
  workflow_dispatch:

jobs:
  branch_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: version
        uses: jaceenet/git-versioning@v1.4.0
        with:
          tag-commit: false          
        env:
          nextVersion: the

      - name: Conventional Changelog Action
        id: nextversion
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: "v"
          skip-commit: "true"
          fallback-version: 1.0.0

      - name: see
        run: echo "${{ steps.nextversion.outputs.nextVersion }}"

      - name: see2
        run: echo "tag ${{ steps.version.outputs.tagVersion }} tag ${{ steps.version.outputs.nextVersion }}"
